LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
# VIALRGB_ENABLE = yes

# VIALRGB_ENABLE=yes requires RGB_MATRIX_ENABLE=yes
# Do not enable RGB_MATRIX_ENABLE together with RGBLIGHT_ENABLE

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes